<a href="https://colab.research.google.com/github/haymidson/freecodecamp-intro-to-numpy/blob/master/Numpy_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
a.ndim

1

In [14]:
b.ndim

2

In [15]:
a.shape

(3,)

In [16]:
b.shape

(2, 3)

In [17]:
a.dtype

dtype('int64')

In [18]:
b.dtype

dtype('float64')

In [19]:
a.itemsize

8

In [20]:
b.itemsize

8

In [22]:
a.size

3

In [23]:
b.size

6

In [3]:
output = np.ones((7,7))
print(output)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [6]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [26]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
# print(z)
z[1,1] = 9
print(z)
output[1:-1, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
output = np.zeros((7,7))

z = np.ones((5, 5))
z[2, 2] = 5

output[1:-1, 1:-1] = z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [31]:
a = np.array([1,2,3])
b == a #using just = is an assignment and a would also be changed
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [41]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 19, 10]))
print(a)
print(np.max(a,axis=1))
b = np.max(a, axis=1).sum()
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8 19 10]]
[ 5 19]
24
